[package]
name = "json2docx"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.87"
docx-rs = "0.4.7"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
base64 = "0.21.2"
gloo-utils = { version = "0.2.0", features = ["serde"] }
